// By convention, actions that end in "_SUCCESS" are assumed to have been the result of a completed
// API call. But since we're doing an optimistic delete, we're hiding loading state.
// So this action name deliberately omits the "_SUCCESS" suffix.
// If it had one, our apiCallsInProgress counter would be decremented below zero
// because we're not incrementing the number of apiCallInProgress when the delete request begins.
// appel api
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
// Actions kanji
export const CREATE_KANJI_SUCCESS = "CREATE_KANJI_SUCCESS";
export const UPDATE_KANJI_SUCCESS = "UPDATE_KANJI_SUCCESS";
export const DELETE_KANJI_SUCCESS = "DELETE_KANJI_SUCCESS";
export const LOAD_KANJIS_SUCCESS = "LOAD_KANJIS_SUCCESS";
export const FILTER_KANJIS_SUCCESS = "FILTER_KANJIS_SUCCESS";
// Actions verb
export const CREATE_VERB_SUCCESS = "CREATE_VERB_SUCCESS";
export const UPDATE_VERB_SUCCESS = "UPDATE_VERB_SUCCESS";
export const DELETE_VERB_SUCCESS = "DELETE_VERB_SUCCESS";
export const LOAD_VERBS_SUCCESS = "LOAD_VERBS_SUCCESS";
export const FILTER_VERBS_SUCCESS = "FILTER_VERBS_SUCCESS";
// Actions NA-adj
export const CREATE_NA_ADJECTIVE_SUCCESS = "CREATE_NA_ADJECTIVE_SUCCESS";
export const UPDATE_NA_ADJECTIVE_SUCCESS = "UPDATE_NA_ADJECTIVE_SUCCESS";
export const DELETE_NA_ADJECTIVE_SUCCESS = "DELETE_NA_ADJECTIVE_SUCCESS";
export const LOAD_NA_ADJECTIVES_SUCCESS = "LOAD_NA_ADJECTIVES_SUCCESS";
export const FILTER_NA_ADJECTIVES_SUCCESS = "FILTER_NA_ADJECTIVES_SUCCESS";
// Actions i-adj
export const CREATE_I_ADJECTIVE_SUCCESS = "CREATE_I_ADJECTIVE_SUCCESS";
export const UPDATE_I_ADJECTIVE_SUCCESS = "UPDATE_I_ADJECTIVE_SUCCESS";
export const DELETE_I_ADJECTIVE_SUCCESS = "DELETE_I_ADJECTIVE_SUCCESS";
export const LOAD_I_ADJECTIVES_SUCCESS = "LOAD_I_ADJECTIVES_SUCCESS";
export const FILTER_I_ADJECTIVES_SUCCESS = "FILTER_I_ADJECTIVES_SUCCESS";
//actions name
export const CREATE_NAME_SUCCESS = "CREATE_NAME_SUCCESS";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const DELETE_NAME_SUCCESS = "DELETE_NAME_SUCCESS";
export const LOAD_NAMES_SUCCESS = "LOAD_NAMES_SUCCESS";
export const FILTER_NAMES_SUCCESS = "FILTER_NAMES_SUCCESS";
//action word
export const CREATE_WORD_SUCCESS = "CREATE_WORD_SUCCESS";
export const UPDATE_WORD_SUCCESS = "UPDATE_WORD_SUCCESS";
export const DELETE_WORD_SUCCESS = "DELETE_WORD_SUCCESS";
export const LOAD_WORDS_SUCCESS = "LOAD_WORDS_SUCCESS";
export const FILTER_WORDS_SUCCESS = "FILTER_WORDS_SUCCESS";
//action particule
export const CREATE_PARTICULE_SUCCESS = "CREATE_PARTICULE_SUCCESS";
export const UPDATE_PARTICULE_SUCCESS = "UPDATE_PARTICULE_SUCCESS";
export const DELETE_PARTICULE_SUCCESS = "DELETE_PARTICULE_SUCCESS";
export const LOAD_PARTICULES_SUCCESS = "LOAD_PARTICULES_SUCCESS";
// action grammar rule
export const CREATE_GRAMMAR_RULE_SUCCESS = "CREATE_GRAMMAR_RULE_SUCCESS";
export const UPDATE_GRAMMAR_RULE_SUCCESS = "UPDATE_GRAMMAR_RULE_SUCCESS";
export const DELETE_GRAMMAR_RULE_SUCCESS = "DELETE_GRAMMAR_RULE_SUCCESS";
export const LOAD_GRAMMAR_RULES_SUCCESS = "LOAD_GRAMMAR_RULES_SUCCESS";
//action sentence
export const CREATE_SENTENCE_SUCCESS = "CREATE_SENTENCE_SUCCESS";
export const UPDATE_SENTENCE_SUCCESS = "UPDATE_SENTENCE_SUCCESS";
export const DELETE_SENTENCE_SUCCESS = "DELETE_SENTENCE_SUCCESS";
export const LOAD_SENTENCES_SUCCESS = "LOAD_SENTENCES_SUCCESS";
export const FILTER_SENTENCES_SUCCESS = "FILTER_SENTENCES_SUCCESS";
// actions counter
export const CREATE_COUNTER_SUCCESS = "CREATE_COUNTER_SUCCESS";
export const UPDATE_COUNTER_SUCCESS = "UPDATE_COUNTER_SUCCESS";
export const DELETE_COUNTER_OPTIMISTIC = "DELETE_COUNTER_OPTIMISTIC";
export const LOAD_COUNTERS_SUCCESS = "LOAD_COUNTERS_SUCCESS";
export const FILTER_COUNTERS_SUCCESS = "FILTER_COUNTERS_SUCCESS";
// action translation
export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const UPDATE_TYPE_OF_OBJECT_SUCCESS = "UPDATE_TYPE_OF_OBJECT_SUCCESS";
export const LOAD_LIST_OBJECT_SUCCESS = "LOAD_LIST_OBJECT_SUCCESS";
export const LOAD_PARTS_SUCCESS = "LOAD_PARTS_SUCCESS";
export const EXTRACT_KANJI_FROM_SENTENCE_SUCCESS =
  "EXTRACT_KANJI_FROM_SENTENCE_SUCCESS";
export const CLEAR_TRANSLATION_SUCCESS = "CLEAR_TRANSLATION_SUCCESS";
// actions suffix
export const CREATE_SUFFIX_SUCCESS = "CREATE_SUFFIX_SUCCESS";
export const UPDATE_SUFFIX_SUCCESS = "UPDATE_SUFFIX_SUCCESS";
export const DELETE_SUFFIX_SUCCESS = "DELETE_SUFFIX_SUCCESS";
export const LOAD_SUFFIXS_SUCCESS = "LOAD_SUFFIXS_SUCCESS";
