export default {
  counters: [],
  grammarRules: [],
  iAdjectives: [],
  kanjis: [],
  naAdjectives: [],
  names: [],
  particules: [],
  sentences: [],
  suffixs: [],
  verbs: [],
  words: [],
  messages: [],
  visitStats: [],
  apiCallsInProgress: 0,
};
